### ISSUE TITLE
release 3.1.0: alwaysRun true option is neglected

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xld-advanced-command-plugin#3] opened 2016-11-04 09:23 UTC
We are using v3.1.0 of the plug-in. If we set the option alwaysRun to true, the step is not executed. Setting reRun order to a value like 10 also does not execute the step.
I attach both the DARs. v2.0 is used as initial deployment. v2.1 is a upgrade. See also the screenshot where you can see that XLD is only updating its repository and not executing the step.
![image001](https://cloud.githubusercontent.com/assets/7237078/20000621/b79ae2d6-a278-11e6-98c5-8e2a06c52a73.png)

**Comment by ltutar** [comment] 2016-11-04 09:26
Uploading DARs is not supported. I am adding the deployot-manifest.xml of both DARs.

```
<?xml version="1.0" encoding="UTF-8"?>
<udm.DeploymentPackage version="2.0" application="cmd_example">
  <orchestrator />
  <satisfiesSignedOffByProductOwner>false</satisfiesSignedOffByProductOwner>
  <deployables>
    <advcmd.Command name="adv_cmd">
      <tags />
      <command>/bin/touch /tmp/testfile_advcmd.2.0</command>
      <createOrder>1</createOrder>
      <destroyOrder>2</destroyOrder>
      <envVars />
      <alwaysRun>true</alwaysRun>
      <noopOrder>3</noopOrder>
    </advcmd.Command>
  </deployables>
  <applicationDependencies />
</udm.DeploymentPackage>

```

```
<?xml version="1.0" encoding="UTF-8"?>
<udm.DeploymentPackage version="2.1" application="cmd_example">
  <orchestrator />
  <satisfiesSignedOffByProductOwner>false</satisfiesSignedOffByProductOwner>
  <deployables>
    <advcmd.Command name="adv_cmd">
      <tags />
      <command>/bin/touch /tmp/testfile_advcmd.2.1</command>
      <createOrder>1</createOrder>
      <envVars />
      <alwaysRun>true</alwaysRun>
    </advcmd.Command>
  </deployables>
  <applicationDependencies />
</udm.DeploymentPackage>

```

**Comment by ltutar** [comment] 2016-11-04 09:41
One remark. If we fill in the command also as noop command
![image002](https://cloud.githubusercontent.com/assets/7237078/20001137/1694c0d4-a27b-11e6-9186-edb9b768dda2.png)
, then it works. 
But as you can see in the screenshot, the text is saying if the noop is empty, then it should use the command. Now we have to add the same command content in command and noop command.

```
<?xml version="1.0" encoding="UTF-8"?>
<udm.DeploymentPackage version="2.0.1" application="cmd_example">
  <orchestrator />
  <satisfiesSignedOffByProductOwner>false</satisfiesSignedOffByProductOwner>
  <deployables>
    <advcmd.Command name="adv_cmd">
      <tags />
      <command>/bin/touch /tmp/testfile_advcmd.2.0</command>
      <createOrder>1</createOrder>
      <noopCommand>/bin/touch /tmp/testfile_advcmd.2.0</noopCommand>
      <envVars />
      <alwaysRun>true</alwaysRun>
    </advcmd.Command>
  </deployables>
  <applicationDependencies />
</udm.DeploymentPackage>

```

**Comment by jdewinne** [comment] 2016-11-05 00:47
Hi Levent,

This is expected behavior. The `NOOP` operation is only triggered when there's no change between the 2 deployables. As you can see, that is not the case because the `command` changed.
I've added [Docker](https://github.com/xebialabs-community/xld-docker-gradle-plugin) configuration to the plugin so you can also test this.
Remark: Are you perhaps looking for the `MODIFY` operation? And don't forget to read the **[WARNING](https://github.com/xebialabs-community/xld-advanced-command-plugin#warning)** in the readme.

Regards,
Joris

**Comment by jdewinne** [comment] 2016-11-05 00:48
Sorry, didn't mean to close

**Comment by ltutar** [comment] 2016-11-05 07:21
Hi Joris,

Yes, I am looking for the MODIFY operation since the content of our `command` is changed with each release. We supply the command with the package number.

**Comment by jdewinne** [comment] 2016-11-11 22:25
Released [3.2.0](https://github.com/xebialabs-community/xld-advanced-command-plugin/releases)

**Comment by ltutar** [comment] 2016-11-11 22:41
thank you. we will test it and let you know.

**Comment by jdewinne** [comment] 2017-01-18 00:28
Closing

**Closed as completed by jdewinne** 2017-01-18 00:28 UTC
